[package]
name = "steel-arguments"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
winnow = "0.7.14"
steel-registry.workspace = true
steel-utils.workspace = true

[lints]
workspace = true
